"""

Revision ID: 62d14f14a038
Revises: 
Create Date: 2025-11-21 19:57:07.227620

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject

# revision identifiers, used by Alembic.
revision = '62d14f14a038'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('encrypted_totp_secret', sa.String(), nullable=True),
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account')),
    sa.UniqueConstraint('email', name=op.f('uq_account_email')),
    sa.UniqueConstraint('phone', name=op.f('uq_account_phone'))
    )
    op.create_table('event',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('registration_policy', sa.Enum('CLOSED', 'REQUIRED', 'OPEN', name='registrationpolicy'), nullable=False),
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event'))
    )
    op.create_table('organizer',
    sa.Column('account_id', sa.GUID(length=16), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_hr', sa.Boolean(), nullable=False),
    sa.Column('is_legal', sa.Boolean(), nullable=False),
    sa.Column('finance_and_law_interest', sa.Boolean(), nullable=False),
    sa.Column('venue_coordination_interest', sa.Boolean(), nullable=False),
    sa.Column('it_interest', sa.Boolean(), nullable=False),
    sa.Column('program_organization_interest', sa.Boolean(), nullable=False),
    sa.Column('partner_relations_interest', sa.Boolean(), nullable=False),
    sa.Column('media_and_marketing_interest', sa.Boolean(), nullable=False),
    sa.Column('hr_interest', sa.Boolean(), nullable=False),
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_organizer_account_id_account'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizer')),
    sa.UniqueConstraint('account_id', name=op.f('uq_organizer_account_id'))
    )
    op.create_table('participant',
    sa.Column('account_id', sa.GUID(length=16), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('address_line1', sa.String(), nullable=False),
    sa.Column('address_line2', sa.String(), nullable=True),
    sa.Column('is_student', sa.Boolean(), nullable=False),
    sa.Column('school_name', sa.String(), nullable=True),
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_participant_account_id_account'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participant')),
    sa.UniqueConstraint('account_id', name=op.f('uq_participant_account_id'))
    )
    op.create_table('segment',
    sa.Column('event_id', sa.GUID(length=16), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('registration_policy', sa.Enum('CLOSED', 'REQUIRED', 'OPEN', name='registrationpolicy'), nullable=False),
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_segment_event_id_event'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_segment'))
    )
    op.create_table('speaker',
    sa.Column('account_id', sa.GUID(length=16), nullable=False),
    sa.Column('introduction', sa.String(), nullable=False),
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_speaker_account_id_account'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speaker')),
    sa.UniqueConstraint('account_id', name=op.f('uq_speaker_account_id'))
    )
    op.create_table('event_registration',
    sa.Column('participant_id', sa.GUID(length=16), nullable=False),
    sa.Column('event_id', sa.GUID(length=16), nullable=False),
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_event_registration_event_id_event'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], name=op.f('fk_event_registration_participant_id_participant'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_registration'))
    )
    op.create_table('segment_registration',
    sa.Column('participant_id', sa.GUID(length=16), nullable=False),
    sa.Column('segment_id', sa.GUID(length=16), nullable=False),
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], name=op.f('fk_segment_registration_participant_id_participant'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['segment_id'], ['segment.id'], name=op.f('fk_segment_registration_segment_id_segment'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_segment_registration'))
    )
    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segment_registration')
    op.drop_table('event_registration')
    op.drop_table('speaker')
    op.drop_table('segment')
    op.drop_table('participant')
    op.drop_table('organizer')
    op.drop_table('event')
    op.drop_table('account')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
